### ISSUE TITLE
Reading float Values?

### ISSUE THREAD

**Issue by aaltaay** [stephan1827/modbusTCP#1]
How can I make it read floating values?

**Comment by stephanstricker** [comment]
There are no floating values in modbus, only bools, and words. You have to do a memory copy and split the float (4 Bytes) into 2 byte values. Then copy it into two registers. Do a merge on the other side. Keep in mind that byte alignment can change on different systems,

**Comment by aaltaay** [comment]
So I'm starting with one variable, byte[] data. 

                float[] word = new float[data.Length / 2];
                for (int x = 0; x < data.Length; x = x + 2)
                {
                    word[x / 2] = data[x] * 256 + data[x + 1];
                }

Do I split the float[] word now into 2 byte[] array? 

When you mean copy it into two registers, can they be integer registers? or how does that work? I looked over alot of documentations, but still no luck.

Thank you so much!
