### ISSUE TITLE
Test App Crashes with "Write Single Register" and "Bits"

### ISSUE THREAD

**Issue by jim88888** [stephan1827/modbusTCP#3]
On the test app, if you click "Bits" followed by "Write Single Register" the app crashes.  It is expecting a 2-byte array and the routine is only supplying a 1-byte array.

**Comment by stephan1827** [comment]
The main issue is that the sample application did not convert the data from bits to byte format. This is fixed in the latest version. I also added an exception when the number of bytes provided to the DLL is not correct.
