### ISSUE TITLE
Modbus FC16 not working

### ISSUE THREAD

**Issue by 0anav** [stephan1827/modbusTCP#4]
Hello, 

I was wondering if you tried to work with FC16 (async). I get no response from the MB device, no matter how i read it, even if i isolate it in a separate project. 
I'm opening the connection, I'm sending fc16, but getting no response. The reading functions work, this is the only issue I've encountered, and I'll look into it further. I was just wondering if it's a known bug.

**Comment by stephan1827** [comment]
I am not aware of any issues with the FC16. Can you try to make some traces with Wireshark.

Stephan

**Comment by stephan1827** [comment]
I have just tried FC16 with my test slave and it works fine on that so its not a general issue. Please send the Wireshark logs if you want to reopen this ticket.
